'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace RDPAccessor.Properties


    ''' <summary>
    '''   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    ''' </summary>
    ' Этот класс создан автоматически классом StronglyTypedResourceBuilder
    ' с помощью такого средства, как ResGen или Visual Studio.
    ' Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    ' с параметром /str или перестройте свой проект VS.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RDPAccessor.Properties.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Close As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property Horizontal_Line As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Horizontal Line", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property logo As Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj, Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
